# Generated by Django 3.2 on 2021-05-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210505_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='jaipu,Rajasthan', max_length=50),
            preserve_default=False,
        ),
    ]
