# Generated by Django 3.2 on 2021-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20210513_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='replies',
        ),
    ]
